linters:
  disable-all: true
  enable:
    - errcheck      # Проверяет обработку ошибок
    - gosimple      # Упрощение кода
    - govet         # Статические ошибки (самое важное!)
    - ineffassign   # Неиспользуемые присваивания
    - staticcheck   # Улучшенный анализатор
    - unused        # Неиспользуемый код

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - errcheck
      text: 'Error return value of \(\(os\.\)?std\(out\|err\)\.\.\*\|\.\*Close\|\.\*Flush\|os\.Remove\(All\)\?\|\.\*print\(f\)\?\)\. is not checked'